### ISSUE TITLE
app for watching air.mozilla video podcasts

### ISSUE THREAD

**Issue by wfwalker** [mozilla/wadi#11]
Richard Milewski thinks we should make an app for watching air.mozilla podcasts

**Comment by wfwalker** [comment]
He writes:
The channel podcast feeds (and RSS feeds) are on the Channels page: https://air.mozilla.org/channels/

**Comment by mykmelez** [comment]
Hmm, if it's podcasts, then High Fidelity can presumably consume them, even if it isn't specialized for doing so. Is @RAMilewski's idea to make an Air Mozilla-specific app?

**Comment by wfwalker** [comment]
I don't think we'd need an AirMo-specific app, no. High Fidelity would need some design for displaying video and controlling video playback.

**Comment by mykmelez** [comment]
Ah, of course, High Fidelity only does audio podcasts at the moment. So this could be a project to add video podcast support to it. Or it could be a project to design and implement a video podcasting app.

**Comment by RAMilewski** [comment]
Actually I think that making the app AirMo specific is a bad idea.  The
video podcast app should be as generic as possible, so community members
around the world could publish their own content.  I'd be glad to help
document how that could be done with FOSS tools.

**Comment by digitarald** [comment]
@RAMilewski we had previous questions about a simple app that feeds from MRSS. I assume we only have RSS from air.mozilla?

**Comment by RAMilewski** [comment]
We have both RSS feeds and "Video Podcast" feeds.  The podcast feeds work
on iOS, and I believe on Android, although I haven't personally tested that.

The easiest place to find them right now is:
https://air.mozilla.org/channels/

-- RIchard

On Mon, Nov 23, 2015 at 10:39 AM, Harald Kirschner <notifications@github.com
