### ISSUE TITLE
create a phantomjs / slimerjs based on current version of gecko

### ISSUE THREAD

**Issue by wfwalker** [mozilla/wadi#15]
jQuery and Ember folks all said they would make use of a phantomjs / slimerjs headless Gecko for testing and integration with Travis-CI.

**Comment by marco-c** [comment]
Do they want slimerjs for Firefox Nightly?

**Comment by wfwalker** [comment]
I guess they want a better way to do headless testing of their JS libraries:
http://phantomjs.org/headless-testing.html

SlimerJS is good because it is based on Gecko instead of WebKit, but bad because it is not really headless. Also, SlimerJS is based on Gecko 31, so increasingly out of date and doesn't include service workers...

**Comment by marco-c** [comment]
> Also, SlimerJS is based on Gecko 31

The info on the slimer.org website is probably outdated: https://github.com/laurentj/slimerjs/commit/8102f3c3a7760896a10b585ad3d9fca9f483228c.
SlimerJS (as Selenium) supports the release version of Firefox (currently 41).

**Comment by wfwalker** [comment]
Oops, thanks for that, I didn't research very deeply. @rorito, can you help clarify what we were hearing in those meetings and how PhatonJS / SlimerJS aren't adequte?

**Comment by rorito** [comment]
@wfwalker I don't think you can run slimer headless?

**Comment by marco-c** [comment]
No, you can't run it headless yet (https://github.com/laurentj/slimerjs/issues/80). From https://slimerjs.org/faq.html:

```
You see windows during the execution of your script? It's normal. Gecko, the rendering engine of Firefox, cannot render web content without a graphical window.
You can launch SlimerJS with xvfb if you are under linux or MacOSx, to have a headless SlimerJS.
There is a hope for future release of SlimerJS, with latest improvements made in Gecko. 
```

You can use `xvfb`, which is also suggested in the Travis docs: http://docs.travis-ci.com/user/gui-and-headless-browsers/
It's used in several Mozilla projects (e.g. https://github.com/mozilla/pluotsorbet, https://github.com/mozilla/firefox-ui-tests, https://github.com/marco-c/web-push/).

**Comment by mykmelez** [comment]
@wfwalker @rorito It'd be useful to clarify with the folks who were requesting this, to ensure we understand exactly what they're asking for, and why it matters. As @marco-c noted, while you can't currently run SlimerJS headlessly directly, you can do so on Linux and Mac with xvfb. And, in my experience, the "headiness" of SlimerJS hasn't been an impediment to using it for testing purposes, both locally and on CI infrastructure like Travis.

So I would want to know more about exactly why those folks want headlessless, i.e. what are the current limitations that they are trying to surmount.

Another possibility, given the statement about SlimerJS being "out-of-date", is that the actual desire is for SlimerJS to be supported, such that it stays up-to-date with the latest versions of Gecko, and it isn't at risk of being broken by Gecko changes.

If that's the case, then the project we would design to achieve that outcome may be much different. (It might also be much bigger than our team, involving the Platform team as a whole, and possibly Mozilla writ large, deciding to support this alternate use of Gecko.)

**Comment by burningTyger** [comment]
You can run pretty much any version of FF with slimerJS. Just give it a path to your version and you're good. Headless doesn't work.
