### ISSUE TITLE
write a WordPress plugin for web push notifications

### ISSUE THREAD

**Issue by wfwalker** [mozilla/wadi#17]
write a WordPress plugin that lets visitors opt into receiving notifications about new blog posts

**Comment by mykmelez** [comment]
Focused and straightforward, with the potential to have a lot of impact. Clear user value: find out when there's something new on a subject they've already expressed an interest in (by going to the site). Clear developer value: re-engage users simply by enabling a plugin, with minimal configuration and no manual hacking required.

I like it a lot!

The only aspect that isn't entirely clear to me is what it means to "let visitors opt in." At first I thought this means the site prompting users itself, but the browser itself may intervene when a site tries to push notifications to users, acting as the user's agent and prompting the user to allow the notifications. And we wouldn't want a user to have to navigate multiple prompts for the same set of notifications. So the exact mechanism for this will depend on the browser interface for notifications.

Either way, this has the potential to define the "best practice" for "frequently updating content" sites, including (but not limited to) blogs.

**Comment by dbialer** [comment]
According to http://w3techs.com/technologies/ - Wordpress is used by 24.9% of all websites.  That is huge.

I think that one thing we need to figure out in the grand scheme of web push is how to make browser notifications inter-operable.  As far a I understand, our push server only works with firefox, and google's only works with chrome.  That puts the burden on the developer to figure out which browser the user is using, whether it can push to it, and how to do it, and how to manage subscribers.  This is where companies like GoRoost come in, but it makes it difficult for developers to manage it themselves, and it places a 'tax' (fee) on pushing.

**Comment by marco-c** [comment]
We could write libraries to make this easier (to abstract the differences between the Firefox and Chrome services).
https://github.com/marco-c/web-push is for nodejs, we could write something similar in PHP.

**Comment by zalun** [comment]
+1 big impact if well promoted not a lot of work

**Comment by darkwing** [comment]
+1 Another big impact type of plugin

**Comment by rorito** [comment]
+1

**Comment by delapuente** [comment]
+1
The CMS user is someone we cannot oversee as they hold almost the 50% of the content in the Web. It's not only Wordpress but Magento, Prestashop and Blogger. Providing offline capabilities to these CMS we cover the most representative portion of the Content Management market and we can impulse the creation of new plugins for the rest of CMS.

**Comment by marco-c** [comment]
I started one here: https://github.com/marco-c/wp-web-push/

**Comment by marti1125** [comment]
Hi @marco-c I woud like to help with this plugin

**Comment by marco-c** [comment]
Awesome! There's a list of issues opened in that repo, they might be a little unclear sometimes because I've used it as a kind of todo list for me, so feel free to ask for clarifications.
