### ISSUE TITLE
IRC client reference app that pushes notifications about new messages

### ISSUE THREAD

**Issue by mykmelez** [mozilla/wadi#19]
An IRC client that pushes notifications about new messages might be a great example of the value of push. The lack of built-in support for persistent sessions is a common complaint about the IRC protocol (perhaps the _most_ common one), and various clients have addressed the problem by maintaining a connection for you.

One use case for a persistent connection is simply to catch up on activity that occurred while you were away upon your return. Push isn't needed for that. But another use case is to find out when interesting activity occurs (in particular, your name is mentioned) while you're away. For that, push is needed.

IRC Cloud has native clients that push notifications. Unsure if they're working on implementing that for their web client. It doesn't currently support them, per the [IRC Cloud FAQ question about notifications](https://www.irccloud.com/faq#faq-notifications).

[Firesea](https://github.com/nickdesaulniers/fxos-irc) might serve as the basis of an implementation.

[Mozlando](https://wiki.mozilla.org/Coincidental_work_weeks/2015_Orlando) would serve as a great testbed, although time seems short for that.

**Comment by marco-c** [comment]
The only problem with Firesea is that it only works in Firefox OS.

Anyway, this is an interesting use case. Re-using Firesea would make the implementation quicker to write.

**Comment by zalun** [comment]
This is slightly related

server
https://github.com/marco-c/mercurius
and the client for irssi
https://github.com/zalun/mercurius-irssi
