### ISSUE TITLE
Platatus v1

### ISSUE THREAD

**Issue by mykmelez** [mozilla/wadi#2]
The [minimal viable prototype](https://github.com/mozilla/platatus/wiki/MVP) of [Platatus](https://github.com/mozilla/platatus), a reference app that describes the standardization/implementation status of web platform features.

**Comment by mykmelez** [comment]
@digitarald Is it no longer accurate to describe the work to which we've committed in Q4 as an MVP? I'm curious about the rename, as it isn't clear what's in scope for this project now that the name doesn't reference the MVP (even though the description still does).

**Comment by digitarald** [comment]
Pardon the dust, I am still experimenting. I thought to track more fine-grained in here, but then again we can't put a milestone on it …

**Comment by mykmelez** [comment]
Hmm, we could have an issue to track a larger set of deliverables around Platatus, f.e. a 1.0 release, in addition to one that tracks the MVP.
