### ISSUE TITLE
Tool to help debugging/testing with web push

### ISSUE THREAD

**Issue by marco-c** [mozilla/wadi#20]
We could write a mock push service usable both to debug/develop apps using web push and to test them.
We could either:
- write it from scratch;
- re-use the Mozilla push service implementation (https://github.com/mozilla-services/autopush).

While writing the web push recipes in https://github.com/mozilla/serviceworker-cookbook, a way to directly control the push service would have helped.

**Comment by digitarald** [comment]
Notes:
- In the MVP for push devtools

**Comment by rorito** [comment]
+1
