### ISSUE TITLE
Implement Service Workers on MDN

### ISSUE THREAD

**Issue by darkwing** [mozilla/wadi#21]
davidwalsh> myk: I think it would be really cool to have a “Save for Offline” button on the page, we save the page with a service worker, and then they can somehow navigate to a list of saved content

myk> davidwalsh: yes, i like it; perhaps it could be button/dropdown menu combination, where the menu shows you your list of saved pages, while the button toggles on/off the current one

We could add service workers for offline reading as well as performance reasons.

**Comment by digitarald** [comment]
Notes:
- @zalun Record history of visited pages and make offline
- Important for India and similar where MDN loadtime is really bad
- @darkwing it's easy

**Comment by brendandahl** [comment]
+1 I'm a bit torn between this and #23 for the dogfood ones, but it seems #23 will probably be done without our help.

**Comment by darkwing** [comment]
I said it would be a bit easier than we think, IMO.

**Comment by zalun** [comment]
+1 best feature if allowed to manage the list

2015-11-24 2:22 GMT+01:00 David Walsh notifications@github.com:

> I said it would be a bit easier than we think, IMO.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/wadi/issues/21#issuecomment-159121523.

## 

London, UK

**Comment by darkwing** [comment]
+1, would solve a long-standing problem with MDN (offline doc reading) and I could help play liaison between the two teams.

**Comment by delapuente** [comment]
+1
I see totally convenient to add this feature to MDN but moreover, it would be precious to add it to other documentation pages as https://readthedocs.org/ (to improve impact) or talk with GitHub to allow explore projects indices in an offline way.

**Comment by groovecoder** [comment]
I heard @darkwing was going to buy a 6-pack for everyone who did :+1: on this.

**Comment by a2sheppy** [comment]
This is something the docs team has talked about many times -- using service workers to allow marking pages for offline use. The service worker can even be used to periodically update the local copy, too. Users being able to pick the content that they need most and have it around all the time would be amazing.

So +1 from me, but it's important to put this through the usual roadmap process and to be sure we don't shove aside more important tasks to assign resources to it. But yes, I love love love this idea. 😍👍🏾

**Comment by marco-c** [comment]
@darkwing would this be a good candidate project for a GSoC or Outreachy?

**Comment by darkwing** [comment]
@marco-c Yes, actually, I think it would be good for GSoC.  I've done it once before, will talk to @digitarald about doing it again.

**Comment by digitarald** [comment]
+1, this seems to be the best project so far for mentoring.

**Comment by darkwing** [comment]
I'm happy to mentor.  I did GSoC two summers ago and it worked out well.  We'll need to ask @lonnen if someone on his team could help; I'm not sure who is taking that helm since @groovecoder and @openjck left MDN.  Maybe @stephaniehobson to co-mentor?

**Comment by marco-c** [comment]
The deadline for the ideas on https://wiki.mozilla.org/Community:SummerOfCode16:Brainstorming is February 19th.
