### ISSUE TITLE
Help support remote newtab

### ISSUE THREAD

**Issue by rorito** [mozilla/wadi#23]

**Comment by zalun** [comment]
+1 helps with openness

**Comment by rorito** [comment]
+1 - Tim's team is actually looking for engineering help to get this launched by end of Jan 2016

**Comment by delapuente** [comment]
We should change that Why - Because we can for something like _Because we should advocate for HTML5 technologies and there are no blockers preventing us to do so_. AFAIK, Chrome is already doing this way, we should definitively push forward HTML5 for the browser chrome.

**Comment by groovecoder** [comment]
:+1: fwiw
