### ISSUE TITLE
Make fxos-components work across browsers

### ISSUE THREAD

**Issue by rorito** [mozilla/wadi#24]
Competitor to Polymer

**Comment by digitarald** [comment]
Notes:
- Thread on b2g

**Comment by anaran** [comment]
anything happening with this one? links appreciated

**Comment by digitarald** [comment]
@anaran we will consider if for your Q2 goals. Web components is an important aspect of the web platform! Any more arguments that you can provide on why this is important and what the goal (responsive, performant, easy to style, etc?) should be, please discuss here.

**Comment by digitarald** [comment]
@anaran we will consider if for your Q2 goals. Web components is an important aspect of the web platform! Any more arguments that you can provide on why this is important and what the goal (responsive, performant, easy to style, etc?) should be, please discuss here.
