### ISSUE TITLE
Write a blog post about real world push example

### ISSUE THREAD

**Issue by zalun** [mozilla/wadi#26]
irssi is missng a good notification system.
It would be great to work on a system which would allow to subscribe to mentions in IRC when running irssi over SSH.
techniques and technologies needed:
- server with following features
  - listening for notification requests from client (i.e. irssi script)
  - push subscription
  - sending push notifications
- service worker for display notifications and handle subscriptn changes
- irssi script as an example client

**Comment by marco-c** [comment]
https://github.com/marco-c/mercurius
https://github.com/zalun/mercurius-irssi

**Comment by mykmelez** [comment]
@marco-c You added the _in progress_ label a couple weeks ago; are you taking the lead on writing this blog post? If so, let's make you the Assignee here so it's clear who's in charge of delivering the post.

**Comment by marco-c** [comment]
Done: https://hacks.mozilla.org/2015/12/web-push-notifications-from-irssi/

**Comment by mykmelez** [comment]
It looks like @zalun was the primary author on this, so I've made him the Assignee (which is useful, even though the project is completed, because it enables us to look back at these issues and get a sense of who did what when).
