### ISSUE TITLE
Mattermost instance with offline web client and push notifications

### ISSUE THREAD

**Issue by mykmelez** [mozilla/wadi#28]
Messaging apps are natural fits for push integration, since users expect to be notified when they receive a new message, whether or not they are currently using the app. [Mattermost](http://www.mattermost.org/) is a group messaging app that has gained some traction as an open-source, self-hosted alternative to Slack.

This project would do three things:
1. Integrate offlining into the Mattermost web client, such that it loads and runs regardless of the current state of the network connection.
2. Integrate push notifications into the Mattermost web client and server, such that the app notifies offline users when they receive a private message, their name is mentioned in a public channel, or another noteworthy event occurs.
3. Deploy an instance of Mattermost with a public #apps channel for discussing web app development.
4. Invite Mozillians to test the instance with their own teams and report their experiences.

Why we can do it:
- Mattermost is open source, so we can see its code and hack on it, including forking it to make changes.
- Mattermost is self-hosted, so we can deploy our own instance of it, including changes that haven't yet been upstreamed.
- Mattermost is deployable via Docker, which makes it straightforward to deploy on Heroku or AWS Elastic Beanstalk.

Why it matters:
- Mattermost integration would make a great case study in adding modern web platform enhancements to an existing web app.
- Mattermost appears to have some traction in the market, including the enterprise (via GitLab integration), so integrating it would disperse the technology more broadly to organizations of heavy web app users, including web and native app developers.
- The Mozilla community would benefit from a better tool for synchronous group messaging, and an instance of Mattermost that Mozillians can evaluate will generate interest in modern web apps.

What success looks like:
- We deploy an instance of Mattermost.
- The instance's web client caches itself to load and run offline.
- The instance pushes notifications to users when they receive a new private message, are mentioned in a public channel, or another noteworthy event occurs.
- The Mattermost project accepts our changes upstream.

What unexpected success beyond our wildest dreams looks like:
- Mozillians adopt our Mattermost instance en masse for synchronous group messaging.
- Mattermost collaborates with Mozilla on a case study in progressive enhancement.
- Organizations using Mattermost contact Mozilla to partner with us on modernization of their own apps.

**Comment by mykmelez** [comment]
Mattermost has now developed a "push notification service", although it only pushes to iOS devices:

https://github.com/mattermost/push-proxy

**Comment by davidascher** [comment]
FYI, we're collaborating with Mattermost as part of the participation &
collaboration work we're doing across MoFo & MoCo.  They specifically are
keen to work w/ us on localization tooling, and we're keen to explore
whether there are features we'd want to add to Mattermost that foster the
kinds of collaborative work we do.  There's likely lots of room for bigger
collaborations.

Would love to keep in touch w.r.t. WADI etc.

**Comment by mykmelez** [comment]
> FYI, we're collaborating with Mattermost as part of the participation & collaboration work we're doing across MoFo & MoCo. They specifically are keen to work w/ us on localization tooling, and we're keen to explore whether there are features we'd want to add to Mattermost that foster the kinds of collaborative work we do. There's likely lots of room for bigger collaborations.

Hey @davidascher, that's great to hear! Are there any docs about your collaborations with Mattermost to date? I'm thinking project plans, lists of requirements, bug reports, or even just brainstorming writeups. I'd love to learn more, and I'm happy to do it by reading stuff! Although I'm also happy to chat sometime if that'd be more productive.

**Comment by marco-c** [comment]
Posting these links here so we don't forget them:
https://github.com/mattermost/platform/issues/1723
https://github.com/npcode/platform/commit/b915a07a9ffb025f02fa46661bdf2c58040983e3

**Comment by davidascher** [comment]
@simonwex do you have notes for @mykmelez above?

**Comment by marco-c** [comment]
https://mattermost.atlassian.net/browse/PLT-2051
