### ISSUE TITLE
Automatically turn "sites" into "apps"

### ISSUE THREAD

**Issue by marco-c** [mozilla/wadi#29]
We could try to heuristically determine when a "site" is a good candidate to be an "app" and automatically cache its shell.
Maybe also cache some content (e.g. content that we heuristically determine the user could be interested in, as in #16).

**Comment by digitarald** [comment]
Notes:
- Could be an add-on or a (proxy) service
- How can this be done on scale without participation (problem of external SWs)

**Comment by marco-c** [comment]
I think we should investigate this, but not set it as one of the things that we will certainly do.

**Comment by delapuente** [comment]
One of the proposals from BMW was to provide a heuristics service where you put the URL of your web app or a zip with its contents and provide some feedback and it is explored to determine how suitable is your app to remain in the Web without switching to a Native App, what are the technologies you could use, the points of improvement, if it is suitable to be offlined and so on. I personally think it is a **huge** project but it is universally useful as we don't push for Web platform directly, we simply study your Web App and provide some meaningful measurements.
