### ISSUE TITLE
Cross-platform React native - web, iOS, android

### ISSUE THREAD

**Issue by rorito** [mozilla/wadi#31]
https://github.com/lmorchard/react-multiplatform/
https://github.com/benoitvallon/react-native-nw-react-calculator

**Comment by digitarald** [comment]
Notes:
- Inspired by project by @lmorchard

**Comment by brendandahl** [comment]
+1 I still would want to look into this more before giving it the full +1, but it seems like an interesting approach. One thing I'm not sure of though, is if a dev is using react are they already likely making a web app as well?

**Comment by rorito** [comment]
@brendandahl I think there are a couple interesting use cases:
1. A dev / startup has a website and they are starting down the path of making a native app for iOS. A lot of said startups are already using React on their website, so React Native sounds appealing
2. A dev that has a background in web development wants to make a native app but is offput by fully learning objective-c/swift/java
3. A small startup that can't afford multiple developers for their native apps. Having a shared codebase for 80% of the shared logic, tests, etc let's them avoid having to re-write the same code and bug fixes for each platform.
4. Being able to have your website, mobile web app, TV app, iOS and Android app all share code is pretty cool

**Comment by rorito** [comment]
+1 btw
