### ISSUE TITLE
A game that works offline and with push

### ISSUE THREAD

**Issue by digitarald** [mozilla/wadi#32]
- A simple game
- Use Playcanvas, ThreeJS or Unity
- VR?
- Offline capable
- Mobile friendly
- Push notifications for either
  - Turn based
  - Collecting resources
  - World events

Make it Mozilla - theme ideas
- Defend the open web
- Sync data
- Learn about the web or reach others
- Hack the web and make it yours

**Comment by marco-c** [comment]
I was thinking about BrowserQuest today, but it doesn't really match our requirements.

**Comment by TimAbraldes** [comment]
> I was thinking about BrowserQuest today, but it doesn't really match our requirements.

We could cache BrowserQuest assets using a Service Worker and the cache API, and push announcements or something, but yeah I agree... BrowserQuest was meant to show off other technologies.

My wife and I are big fans of [Simon Tatham's Portable Puzzle Collection](http://www.chiark.greenend.org.uk/~sgtatham/puzzles/), maybe we could port the backend to make it possible to easily write new puzzle games that have a great offline experience? We could also perhaps push high score information or announcements when new puzzles get added?

**Comment by TimAbraldes** [comment]
+1 to this.

A game would be super fun to write. Additionally, "gaming" is a super important category in the mobile app development world. If we're able to successfully demonstrate an enjoyable, engaging mobile gaming experience, it's likely that mobile app developers will be more interested in using the same techniques and technologies.

**Comment by marco-c** [comment]
+1

**Comment by delapuente** [comment]
+1

I would love to make a project like this. It could be very motivational and interesting, but, trying to be focused and meaningful, I think we should focus on add caching capabilities to [Phaser](https://feedly.com/) which have a great base of users (or whichever game engine we choose).

Some ideas coming to my head: a turn based game (where push notifications are very meaningful as your are waiting for your adversary) or an _o-game_ like game (where putting alerts is vital).

**Comment by TimAbraldes** [comment]
> I would love to make a project like this. It could be very motivational and interesting, but, trying to be focused and meaningful, I think we should focus on add caching capabilities to [Phaser](http://phaser.io/) which have a great base of users (or whichever game engine we choose).

Yeah, that's a good point. If we want to maximize our impact, we should extend a framework that already has a developer base. That way lots of _other_ people can write games that show off the capabilities of these new web technologies and can compete with native mobile games.

**Comment by marco-c** [comment]
@arcturus is adding service worker support to this game https://github.com/arcturus/ldjam-32-fxos (which uses Phaser).

**Comment by delapuente** [comment]
For this, we are talking with our colleagues from games in Mozilla about helping game developers to decrease initial fingerprint of the game by streaming content based on modern web technologies.
