### ISSUE TITLE
RSS reader app

### ISSUE THREAD

**Issue by TimAbraldes** [mozilla/wadi#34]
When Google Reader disappeared, a vacuum was created that was partially filled by various other apps and services. I personally use NewsBlur, but that doesn't work well on mobile (probably because they expect mobile users to install the various apps).

It might be possible to create a minimal rss reader webapp with a great offline experience on top of Service Worker and Push

**Comment by marco-c** [comment]
I wanted to file this as well, it would be really useful to have news automatically cached for when you're offline.
This could be a nice demo for BackgroundSync (once it will be implemented).

**Comment by delapuente** [comment]
I use https://feedly.com (not open source)

**Comment by marti1125** [comment]
@marco-c make a nodejs app (with hapijs I think...) can I take this?

**Comment by marco-c** [comment]
@marti1125 you're definitely welcome to work on this if you want!

**Comment by marti1125** [comment]
Sure :)

**Comment by marti1125** [comment]
Hi @marco-c I'm starting https://github.com/marti1125/rss-offline is an expressjs. could you help with the app for example open issues about the final result of the app etc...

**Comment by marco-c** [comment]
@marti1125 I'm not really an UX expert, I'd start building the app and then we can figure out what to improve later.
