### ISSUE TITLE
Maps app

### ISSUE THREAD

**Issue by TimAbraldes** [mozilla/wadi#35]
To my knowledge (and I've tried a number of them), none of the popular maps webapps are very usable on mobile. It might be possible for us to use the OpenStreetMap dataset and create a mobile-friendly maps app with a great offline experience on top of ServiceWorker and Push.

This is probably way more effort than we're willing to sign up for, but I figured I'd file it for completeness.

**Comment by marco-c** [comment]
We once started writing something like this during a work week: https://github.com/fzzzy/ptolemy
It could have an impact, since the currently available apps for Firefox OS offer a very poor experience, but it also requires a lot of work to achieve good enough quality.

**Comment by delapuente** [comment]
Maybe http://www.openstreetmap.org
