### ISSUE TITLE
conference scheduler with offline and push

### ISSUE THREAD

**Issue by mykmelez** [mozilla/wadi#36]
We could build a conference scheduling app that offlines its app shell, offlines and synchronizes data, and pushes notifications when changes occur to your scheduled events. Or we could integrate these capabilities into an existing scheduling app, by contributing to an open source app or working with a partner on a prioprietary app like Sched. Potentially dogfood, if Mozilla uses the app to schedule a conference like a Coincidental Work Week.

**Comment by daleharvey** [comment]
https://developer.mozilla.org/en-US/demos/detail/the-conference seems like a potential candidate for this, it won the mozilla dev derby a while ago, it works offline but doesnt have push

https://developer.cdn.mozilla.net/media/uploads/demos/P/a/Parashuram/bb0506b9546323f0247bbbedeb358033/the-conference_1356465662_demo_package/index.html#home/schedule
