### ISSUE TITLE
distribute Salva's amazing SW101 handout

### ISSUE THREAD

**Issue by wfwalker** [mozilla/wadi#37]
@delapuente made an amazing PDF handout showing lifecycle of service workers. It needs to get much wider distribution, somewhere.

**Comment by delapuente** [comment]
I talked to Chris Mills to include in the MDN. He made me some suggestions about splitting the content to illustrate the text and to provide a link to a high quality PDF version. Moreover, I will show it tomorrow at [Codemotion](http://2015.codemotion.es/).

**Comment by marco-c** [comment]
@delapuente any news?

**Comment by delapuente** [comment]
I embedded the 101 in the [MDN page about Using Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) and sent the changes but I'm waiting for Chris to review.

How do you think I can publicize this more?

**Comment by marco-c** [comment]
I think adding it to MDN is enough!
