### ISSUE TITLE
Find projects that could benefit from Oghliner and send PRs to make them use it

### ISSUE THREAD

**Issue by marco-c** [mozilla/wadi#38]
`oghliner` can be a really useful tool, but we need to make people use it to gain some momentum.

**Comment by marco-c** [comment]
One could be #3.

**Comment by mykmelez** [comment]
Shower is the only one I know of outside Mozilla projects. (Inside, there's FireKey and EggTimer, but they both already use Oghliner.) This'd be especially interesting if there's an app with an existing, significant userbase.
