### ISSUE TITLE
Documentation for karma-sw-mocha

### ISSUE THREAD

**Issue by marco-c** [mozilla/wadi#39]
@delapuente wrote a karma adapter for testing service worker code: https://github.com/delapuente/karma-sw-mocha
To make it really useful we should document it.

**Comment by delapuente** [comment]
And decouple, in order you don't be forced to use with mocha (or provide alternatives).

**Comment by delapuente** [comment]
It's documented and decoupled and I'm writing a blog post about how to use it. We use it in oghliner.
