### ISSUE TITLE
create microsite / landing page for progressive web app developers

### ISSUE THREAD

**Issue by wfwalker** [mozilla/wadi#40]
we could create something like https://dev.windows.com/en-us

It might even be another view onto the platatus .MD files, where we already link to docs at MDN

**Comment by darkwing** [comment]
There was a rumored "Developer Program" about a year ago which never came to fruition but I do think that all of the Mozilla dev projects need one site to tie them together.  A sort of "Hacks" + "MDN" + "Platatus" + ... site.  If it's all static content it could live in MDN as a "zone".

**Comment by darkwing** [comment]
And actually, Bill, I think that the MDN homepage should be like the link that you've cited above.  Right now the MDN homepage is just repeated information.  I think we should get an Information Architecture expert together with a designer and tie all of these types of projects on the MDN homepage.

**Comment by delapuente** [comment]
Agree with both of you. First, a HUB for Progressive Web App Developers would be great but maybe what we need is a rethink of MDN (as @darkwing suggests) to become some kind of learning center. Not only with technical information but putting effort on tutorials and adapted to several audiences.

**Comment by delapuente** [comment]
Well, the [Progressive Application HQ](https://github.com/mozilla/progressive-apps-hq/) is aimed to create this kind of site.
