### ISSUE TITLE
add a feature to Firefox to highlight offline-possible items in bookmarks list or open tabs

### ISSUE THREAD

**Issue by wfwalker** [mozilla/wadi#42]
if we know that a particular tab is open to a domain with a SW registered, and that SW has stuff cached, then we could guess it will work offline, and show that fact in the UI somehow? Same for bookmarks?

**Comment by delapuente** [comment]
Maybe we can add this feature to the blank tab (the one with the tiled most visited sites).

**Comment by mykmelez** [comment]
We might be able to implement something like this as a [WebExtension](https://wiki.mozilla.org/WebExtensions).
