### ISSUE TITLE
Create a (broccoli/ember)-oghliner addon

### ISSUE THREAD

**Issue by marco-c** [mozilla/wadi#43]

**Comment by rorito** [comment]
+1

**Comment by mykmelez** [comment]
How common is it to deploy Ember apps to GitHub Pages? This would be useful if GitHub Pages is a common deployment target. Otherwise, it would make more sense to provide a provider-agnostic offlining module, like sw-toolbox or ServiceWorkerWare.

**Comment by jonathanKingston** [comment]
@mykmelez it's certainly not a common deployment target, the likes of ember-deploy have addons to push to set locations. Despite ember-deploy being new I think the uptake of this addon demonstrates the usage: https://github.com/jrowlingson/ember-cli-deploy-github

I had considered using github for the likes of fxos app deployment but then the parts oghliner give will likely best covered by ember-cli-deploy-github anyway.

**Comment by delapuente** [comment]
@marco-c If you're worried about the scope of this project as a candidate for GSoC we could extend it by rewording it to "provide Oghliner plugins for the most important / relevant client-side frameworks" and split the project into a research stage (where we determine 3 of the most important / relevant frameworks) and several short development cycles (which include coding, testing and documentation). What do you think?
