### ISSUE TITLE
Best of Planet blog post stream

### ISSUE THREAD

**Issue by mykmelez** [mozilla/wadi#44]
There's a ton of great content on Planet Mozilla, and some of it is targeted to web developers generally, but it's hard to find those posts within the flood of posts about Mozilla-specific subjects. Meanwhile, Hacks does a great job of soliciting, editing, and publishing articles for web developers, but it's high-touch and thus low-volume.

Web developers would benefit from an intermediate stream of selected articles from Planet Mozilla that address subjects of interest to them. A kind of "Best of Planet," where by "best" I mean "best suited for web developers," not a judgement about quality. It would be _curated_ but not _solicited_ nor _edited_, as we wouldn't ask writers to write for it, nor would we edit the articles they write. We would just pan the Planet streambeds for the webdev gold flakes within the blogging sandbanks.

Riffing on the idea a bit: it might also include posts from Hacks, which are (nearly?) all relevant to web developers. And perhaps over time it could grow to incorporate interesting posts from around the web, becoming something more akin to a Best of Web (on Web Development). I can also imagine a sibling "Best of Web" for business-related subjects (discovery, monetization, tracking, ads, etc.). But I would start with a single stream focused on content from Planet.

**Comment by marco-c** [comment]
This is a very interesting idea. I'd love it.

**Comment by mykmelez** [comment]
If Wordpress can be used to aggregate/syndicate posts, then it would also be interesting to see if there's a way to combine this project with #16 and #17, by setting up a Wordpress installation that aggregates/syndicates the Best of Planet posts and uses Service Workers and Push to offline them and notify users about updates.
