### ISSUE TITLE
Add a progressive apps section to MDN to educate about modern web applications development

### ISSUE THREAD

**Issue by delapuente** [mozilla/wadi#49]
Currently, a search of "[progressive apps](https://developer.mozilla.org/en-US/search?q=progressive+apps)" does not show results. Moreover, the main page of [MDN](https://developer.mozilla.org/en/) has no references to Web Applications. To get a link related to the development of Web applications, we must click on [more under _Web Platform_](https://developer.mozilla.org/en-US/docs/Web) in the main page of the MDN, there we can find the link [Developing Web applications](https://developer.mozilla.org/en-US/Apps) under the _Other Topics_ section.

Once there, it turns out to be the [App Center](https://developer.mozilla.org/en-US/Apps) which put focus on Firefox OS apps and Marketplace instead of universal Web Applications.

A real (Progressive) Web Applications section must be added to the MDN. This section should serve as a meeting point for the MDN documentation related with progressive web apps but also a HUB for tools, resources and related publications.

**Comment by delapuente** [comment]
There is a draft in https://github.com/mozilla/progressive-apps-hq/ and a live view in http://mozilla.github.io/progressive-apps-hq/

**Comment by delapuente** [comment]
The site is focused on beginner and medium Web App developers. For beginners, it is possible to not know what a progressive application is so the site highlights features. These features lead to _by-feature_ landing pages, elaborating on each characteristic and exposing some use cases. A list of the set of technologies needed to implement the feature is provided in addition to a list of external resources.

_By-technology_ landing pages are available. These summarize each technology and provide a list of resources.

**Comment by TimAbraldes** [comment]
> A real (Progressive) Web Applications section must be added to the MDN. This section should serve as a meeting point for the MDN documentation related with progressive web apps but also a HUB for tools, resources and related publications.

Indeed. MDN is an important resource for developers and should definitely include information about building Web Apps. Additionally, it could link to (and be linked from) Platatus, serviceworker-cookbook, oghliner, etc.

**Comment by delapuente** [comment]
Related with #40

**Comment by wfwalker** [comment]
Chris Mills is making progress on this here https://developer.mozilla.org/en/Apps
