### ISSUE TITLE
Weathersaurus app

### ISSUE THREAD

**Issue by digitarald** [mozilla/wadi#5]
@TimAbraldes started [weathersaurus](https://github.com/TimAbraldes/weathersaurus) as demo for service workers.

**Comment by mykmelez** [comment]
@digitarald Can you describe a project that we might undertake with the Weathersaurus app? For example, a set of features we might implement, or some documentation we might write (on MDN, or in a blog post) that uses the app to demonstrate the functionality it describes.

The issues in this repository are intended to describe projects, i.e. time-constrained endeavors with a specific outcome, like #1, which describes the v1 release of Oghliner, and #2, which describes the MVP of Platatus. So this issue should describe something specific that we're doing (or thinking about doing) with Weathersaurus.

Also, per the [README](https://github.com/mozilla/wadi/blob/master/README.md), projects are automatically backlogged if they don't have a milestone and assignee. Here you've added a _backlog_ tag, but you've set an assignee, although you haven't set a milestone. I would leave both _Milestone_ and _Assignee_ fields blank until we identify a project and someone commits to doing it within a particular timeframe.
