### ISSUE TITLE
Write an article about enabling HTTPS for WordPress websites

### ISSUE THREAD

**Issue by marco-c** [mozilla/wadi#55]
We could use it as a reference in our WordPress plugins, citing it when SSL is not enabled.

Related:
https://github.com/tollmanz/lets-encrypt-wp
http://www.wpbeginner.com/wp-tutorials/how-to-add-free-ssl-in-wordpress-with-lets-encrypt/
http://www.wpbeginner.com/wp-tutorials/how-to-add-ssl-and-https-in-wordpress/
https://make.wordpress.org/support/user-manual/web-publishing/https-for-wordpress/

@sole might be interested.

**Comment by sole** [comment]
Hey yes

That's more or less the crux of my talk. I want to write a post for Hacks detailing this.

Do you plan to suggest using Lets Encrypt, or any other certificate authority? Mine would just cover L-E.

**Comment by marco-c** [comment]
My plan was a generic article containing info about HTTPS in WordPress, with a section about Let's Encrypt.

I wanted to add a link to the article in the warning in my plugin:
![warning](https://cloud.githubusercontent.com/assets/1616846/13106238/13c6da20-d55f-11e5-9988-cf58a498ca56.png)

If you're going to write a Hacks post, I can definitely use it for the Let's Encrypt section.

**Comment by sole** [comment]
for anyone reading: we coordinated offline, we'll try to get my article before the plugin is released :)
