### ISSUE TITLE
recommend best practices for using HTTP/2 with progressive web apps and popular frameworks

### ISSUE THREAD

**Issue by wfwalker** [mozilla/wadi#56]
if lots of small incremental updates are cheap, do we stop bundling all our JS into one big blob? Does Redux look different?

**Comment by mykmelez** [comment]
> if lots of small incremental updates are cheap, do we stop bundling all our JS into one big blob?

Yes! HTTP/2 was explicitly designed to address the root causes of the HTTP/1 perf problems for which bundling is a workaround. If you serve your asserts via HTTP/2, you no longer need to bundle assets of any kind.

> Does Redux look different?

Perhaps. I'm not the Redux expert, but [server rendering](http://redux.js.org/docs/recipes/ServerRendering.html) seems to assume you'll use "your build tool of choice (Webpack, Browserify, etc.) to compile a bundle file into dist/bundle.js." That's no longer necessary, but it's still possible, so Redux doesn't have to change. And Redux may already support unbundled script, in which case it's only the docs that have to change.

**Comment by mykmelez** [comment]
>  recommend best practices for using HTTP/2 with progressive web apps and popular frameworks

Perhaps this is something for the new MDN hub?
