### ISSUE TITLE
offline High Fidelity podcasting app

### ISSUE THREAD

**Issue by wfwalker** [mozilla/wadi#6]
Finish adding offlining with serviceworker support to https://github.com/mozilla/high-fidelity

**Comment by mykmelez** [comment]
This may depend on the project to convert the app to Ember. That project was on the https://github.com/mozilla/high-fidelity/tree/ember-cli-conversion branch at one point, but I think it's now been merged to master.

**Comment by mykmelez** [comment]
@marco-c has used https://www.npmjs.com/package/broccoli-serviceworker to offline another Ember app. It may be possible to offline High Fidelity the same way.

**Comment by marco-c** [comment]
Yes, if we finished up the ember-cli conversion, using broccoli-serviceworker should be really easy.

**Comment by digitarald** [comment]
Per @zalun, this is currently blocked by loading mixed content - the podcasts. The previous app was packaged/privileged and used `systemXHR`. A simple but bandwidth-intense solution would a proxy that streams the content for the app.

**Comment by digitarald** [comment]
Another blocker is the missing design and that we have no responsive components library. Polymer might be an option here when we agree with Material design as a starting point.
