### ISSUE TITLE
Dropbox client using service workers and the cache API

### ISSUE THREAD

**Issue by marco-c** [mozilla/wadi#7]
This app could show more complex use cases of service workers and the cache API.

It would automatically cache files when the user opens them, limit the amount of cached data, periodically clear the cache.

**Comment by mykmelez** [comment]
The Dropbox API is reasonably comprehensive, and it appears to set CORS headers that enable cross-origin access, so it should be possible to do some interesting things with it.

Is the app in question intended to be a [file manager](https://en.wikipedia.org/wiki/File_manager) app like the one that Dropbox provides at https://www.dropbox.com/home, except that it can cache files?

**Comment by marco-c** [comment]
> Is the app in question intended to be a file manager app like the one that Dropbox provides at https://www.dropbox.com/home, except that it can cache files?

Exactly. The mobile version for Firefox OS isn't really good compared to the Android native app. Caching is a really useful feature (for example if you want to re-open a file you've opened before but you're currently offline) which is missing.
It also allows us to show a somewhat complex usage of the Cache API (e.g. cache on-demand; strategy to evict cache entries to avoid wasting too much space).
