### ISSUE TITLE
App to track watching TV series

### ISSUE THREAD

**Issue by marco-c** [mozilla/wadi#8]
https://github.com/marco-c/watchy

This is an ember app, it could be useful as an example of broccoli-serviceworker usage and could be useful to drive broccoli-serviceworker development.

**Comment by mykmelez** [comment]
@marco-c is there a document describing the intended features of the app? Or perhaps you could describe them here? I'm just trying to get a sense for what the app would do.

**Comment by marco-c** [comment]
The app would allow you to track the shows you're watching. You can add shows to a list, mark episodes as seen/unseen, see statistics about your series watching activity, read show/episode descriptions. The shows you're watching will be cached to allow users to use the app while offline.
Users can register to a show to get a notification when a new episode is aired.

There are several sources of information about shows, like http://trakt.tv/ and http://thetvdb.com/, both provide an API. I'd use TheTVDB since "All content and images on the site have been contributed by our users, and are licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

There are several popular apps for Android (each has 1000000-5000000 users):
https://play.google.com/store/apps/details?id=com.battlelancer.seriesguide - https://github.com/UweTrottmann/SeriesGuide
https://play.google.com/store/apps/details?id=fema.serietv2
https://play.google.com/store/apps/details?id=com.tozelabs.tvshowtime
